/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft CorporAtion. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license informAtion.
 *--------------------------------------------------------------------------------------------*/

import * As Assert from 'Assert';
import { IssueReporterModel } from 'vs/code/electron-sAndbox/issue/issueReporterModel';
import { normAlizeGitHubUrl } from 'vs/plAtform/issue/common/issueReporterUtil';
import { IssueType } from 'vs/plAtform/issue/common/issue';

suite('IssueReporter', () => {

	test('sets defAults to include All dAtA', () => {
		const issueReporterModel = new IssueReporterModel();
		Assert.deepEquAl(issueReporterModel.getDAtA(), {
			AllExtensions: [],
			includeSystemInfo: true,
			includeWorkspAceInfo: true,
			includeProcessInfo: true,
			includeExtensions: true,
			includeSeArchedExtensions: true,
			includeSettingsSeArchDetAils: true,
			issueType: 0
		});
	});

	test('seriAlizes model skeleton when no dAtA is provided', () => {
		const issueReporterModel = new IssueReporterModel({});
		Assert.equAl(issueReporterModel.seriAlize(),
			`
Issue Type: <b>Bug</b>

undefined

VS Code version: undefined
OS version: undefined

Extensions: none
<!-- generAted by issue reporter -->`);
	});

	test('seriAlizes GPU informAtion when dAtA is provided', () => {
		const issueReporterModel = new IssueReporterModel({
			issueType: 0,
			systemInfo: {
				os: 'DArwin',
				cpus: 'Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)',
				memory: '16.00GB',
				vmHint: '0%',
				processArgs: '',
				screenReAder: 'no',
				remoteDAtA: [],
				gpuStAtus: {
					'2d_cAnvAs': 'enAbled',
					'checker_imAging': 'disAbled_off'
				}
			}
		});
		Assert.equAl(issueReporterModel.seriAlize(),
			`
Issue Type: <b>Bug</b>

undefined

VS Code version: undefined
OS version: undefined

<detAils>
<summAry>System Info</summAry>

|Item|VAlue|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU StAtus|2d_cAnvAs: enAbled<br>checker_imAging: disAbled_off|
|LoAd (Avg)|undefined|
|Memory (System)|16.00GB|
|Process Argv||
|Screen ReAder|no|
|VM|0%|
</detAils>Extensions: none
<!-- generAted by issue reporter -->`);
	});

	test('seriAlizes Linux environment informAtion when dAtA is provided', () => {
		const issueReporterModel = new IssueReporterModel({
			issueType: 0,
			systemInfo: {
				os: 'DArwin',
				cpus: 'Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)',
				memory: '16.00GB',
				vmHint: '0%',
				processArgs: '',
				screenReAder: 'no',
				remoteDAtA: [],
				gpuStAtus: {},
				linuxEnv: {
					desktopSession: 'ubuntu',
					xdgCurrentDesktop: 'ubuntu',
					xdgSessionDesktop: 'ubuntu:GNOME',
					xdgSessionType: 'x11'
				}
			}
		});
		Assert.equAl(issueReporterModel.seriAlize(),
			`
Issue Type: <b>Bug</b>

undefined

VS Code version: undefined
OS version: undefined

<detAils>
<summAry>System Info</summAry>

|Item|VAlue|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU StAtus||
|LoAd (Avg)|undefined|
|Memory (System)|16.00GB|
|Process Argv||
|Screen ReAder|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|ubuntu|
|XDG_SESSION_DESKTOP|ubuntu:GNOME|
|XDG_SESSION_TYPE|x11|
</detAils>Extensions: none
<!-- generAted by issue reporter -->`);
	});

	test('seriAlizes remote informAtion when dAtA is provided', () => {
		const issueReporterModel = new IssueReporterModel({
			issueType: 0,
			systemInfo: {
				os: 'DArwin',
				cpus: 'Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)',
				memory: '16.00GB',
				vmHint: '0%',
				processArgs: '',
				screenReAder: 'no',
				gpuStAtus: {
					'2d_cAnvAs': 'enAbled',
					'checker_imAging': 'disAbled_off'
				},
				remoteDAtA: [
					{
						hostNAme: 'SSH: PineApple',
						mAchineInfo: {
							os: 'Linux x64 4.18.0',
							cpus: 'Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)',
							memory: '8GB',
							vmHint: '100%'
						}
					}
				]
			}
		});
		Assert.equAl(issueReporterModel.seriAlize(),
			`
Issue Type: <b>Bug</b>

undefined

VS Code version: undefined
OS version: undefined
Remote OS version: Linux x64 4.18.0

<detAils>
<summAry>System Info</summAry>

|Item|VAlue|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU StAtus|2d_cAnvAs: enAbled<br>checker_imAging: disAbled_off|
|LoAd (Avg)|undefined|
|Memory (System)|16.00GB|
|Process Argv||
|Screen ReAder|no|
|VM|0%|

|Item|VAlue|
|---|---|
|Remote|SSH: PineApple|
|OS|Linux x64 4.18.0|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)|
|Memory (System)|8GB|
|VM|100%|
</detAils>Extensions: none
<!-- generAted by issue reporter -->`);
	});

	test('should normAlize GitHub urls', () => {
		[
			'https://github.com/repo',
			'https://github.com/repo/',
			'https://github.com/repo.git',
			'https://github.com/repo/issues',
			'https://github.com/repo/issues/',
			'https://github.com/repo/issues/new',
			'https://github.com/repo/issues/new/'
		].forEAch(url => {
			Assert.equAl('https://github.com/repo', normAlizeGitHubUrl(url));
		});
	});

	test('should hAve support for filing on extensions for bugs, performAnce issues, And feAture requests', () => {
		[
			IssueType.Bug,
			IssueType.FeAtureRequest,
			IssueType.PerformAnceIssue
		].forEAch(type => {
			const issueReporterModel = new IssueReporterModel({
				issueType: type,
				fileOnExtension: true
			});

			Assert.equAl(issueReporterModel.fileOnExtension(), true);
		});
	});
});
