/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft CorporAtion. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license informAtion.
 *--------------------------------------------------------------------------------------------*/

import { KeyboArdLAyoutContribution } from 'vs/workbench/services/keybinding/browser/keyboArdLAyouts/_.contribution';


KeyboArdLAyoutContribution.INSTANCE.registerKeyboArdLAyout({
	lAyout: { id: 'com.Apple.keylAyout.USExtended', lAng: 'en', locAlizedNAme: 'ABC - Extended' },
	secondAryLAyouts: [],
	mApping: {
		KeyA: ['A', 'A', '¯', '̄', 4],
		KeyB: ['b', 'B', '˘', '̆', 4],
		KeyC: ['c', 'C', '¸', '̧', 4],
		KeyD: ['d', 'D', 'ð', 'Ð', 0],
		KeyE: ['e', 'E', '´', '́', 4],
		KeyF: ['f', 'F', 'ƒ', '', 0],
		KeyG: ['g', 'G', '©', '‸', 8],
		KeyH: ['h', 'H', 'ˍ', '̱', 4],
		KeyI: ['i', 'I', 'ʼ', '̛', 4],
		KeyJ: ['j', 'J', '˝', '̋', 4],
		KeyK: ['k', 'K', '˚', '̊', 4],
		KeyL: ['l', 'L', '-', '̵', 4],
		KeyM: ['m', 'M', '˛', '̨', 4],
		KeyN: ['n', 'N', '˜', '̃', 4],
		KeyO: ['o', 'O', 'ø', 'Ø', 0],
		KeyP: ['p', 'P', ',', '̦', 4],
		KeyQ: ['q', 'Q', 'œ', 'Œ', 0],
		KeyR: ['r', 'R', '®', '‰', 0],
		KeyS: ['s', 'S', 'ß', '', 0],
		KeyT: ['t', 'T', 'þ', 'Þ', 0],
		KeyU: ['u', 'U', '¨', '̈', 4],
		KeyV: ['v', 'V', 'ˇ', '̌', 4],
		KeyW: ['w', 'W', '˙', '̇', 4],
		KeyX: ['x', 'X', '.', '̣', 4],
		KeyY: ['y', 'Y', '¥', '', 0],
		KeyZ: ['z', 'Z', 'ˀ', '̉', 4],
		Digit1: ['1', '!', '¡', '⁄', 0],
		Digit2: ['2', '@', '™', '€', 0],
		Digit3: ['3', '#', '£', '‹', 0],
		Digit4: ['4', '$', '¢', '›', 0],
		Digit5: ['5', '%', '§', '†', 0],
		Digit6: ['6', '^', 'ˆ', '̂', 4],
		Digit7: ['7', '&', '¶', '‡', 0],
		Digit8: ['8', '*', '•', '°', 0],
		Digit9: ['9', '(', 'ª', '·', 0],
		Digit0: ['0', ')', 'º', '‚', 0],
		Enter: [],
		EscApe: [],
		BAckspAce: [],
		TAb: [],
		SpAce: [' ', ' ', ' ', ' ', 0],
		Minus: ['-', '_', '–', '—', 0],
		EquAl: ['=', '+', '≠', '±', 0],
		BrAcketLeft: ['[', '{', '“', '”', 0],
		BrAcketRight: [']', '}', '‘', '’', 0],
		BAckslAsh: ['\\', '|', '«', '»', 0],
		Semicolon: [';', ':', '…', '№', 8],
		Quote: ['\'', '"', 'æ', 'Æ', 0],
		BAckquote: ['`', '~', '`', '̀', 4],
		CommA: [',', '<', '≤', '„', 0],
		Period: ['.', '>', '≥', 'ʔ', 8],
		SlAsh: ['/', '?', '÷', '¿', 0],
		CApsLock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		Insert: [],
		Home: [],
		PAgeUp: [],
		Delete: [],
		End: [],
		PAgeDown: [],
		ArrowRight: [],
		ArrowLeft: [],
		ArrowDown: [],
		ArrowUp: [],
		NumLock: [],
		NumpAdDivide: ['/', '/', '/', '/', 0],
		NumpAdMultiply: ['*', '*', '*', '*', 0],
		NumpAdSubtrAct: ['-', '-', '-', '-', 0],
		NumpAdAdd: ['+', '+', '+', '+', 0],
		NumpAdEnter: [],
		NumpAd1: ['1', '1', '1', '1', 0],
		NumpAd2: ['2', '2', '2', '2', 0],
		NumpAd3: ['3', '3', '3', '3', 0],
		NumpAd4: ['4', '4', '4', '4', 0],
		NumpAd5: ['5', '5', '5', '5', 0],
		NumpAd6: ['6', '6', '6', '6', 0],
		NumpAd7: ['7', '7', '7', '7', 0],
		NumpAd8: ['8', '8', '8', '8', 0],
		NumpAd9: ['9', '9', '9', '9', 0],
		NumpAd0: ['0', '0', '0', '0', 0],
		NumpAdDecimAl: ['.', '.', '.', '.', 0],
		IntlBAckslAsh: ['§', '±', '§', '±', 0],
		ContextMenu: [],
		NumpAdEquAl: ['=', '=', '=', '=', 0],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		AudioVolumeMute: [],
		AudioVolumeUp: ['', '=', '', '=', 0],
		AudioVolumeDown: [],
		NumpAdCommA: [],
		IntlRo: [],
		KAnAMode: [],
		IntlYen: [],
		ControlLeft: [],
		ShiftLeft: [],
		AltLeft: [],
		MetALeft: [],
		ControlRight: [],
		ShiftRight: [],
		AltRight: [],
		MetARight: []
	}
});
