/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft CorporAtion. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license informAtion.
 *--------------------------------------------------------------------------------------------*/

import { KeyboArdLAyoutContribution } from 'vs/workbench/services/keybinding/browser/keyboArdLAyouts/_.contribution';


KeyboArdLAyoutContribution.INSTANCE.registerKeyboArdLAyout({
	lAyout: { id: 'com.Apple.keylAyout.ItAliAn-Pro', lAng: 'it', locAlizedNAme: 'ItAliAn' },
	secondAryLAyouts: [],
	mApping: {
		KeyA: ['A', 'A', 'å', 'Å', 0],
		KeyB: ['b', 'B', '∫', 'Í', 0],
		KeyC: ['c', 'C', '©', 'Á', 0],
		KeyD: ['d', 'D', '∂', '˘', 0],
		KeyE: ['e', 'E', '€', 'È', 0],
		KeyF: ['f', 'F', 'ƒ', '˙', 0],
		KeyG: ['g', 'G', '∞', '˚', 0],
		KeyH: ['h', 'H', '∆', '¸', 0],
		KeyI: ['i', 'I', 'œ', 'Œ', 0],
		KeyJ: ['j', 'J', 'ª', '˝', 0],
		KeyK: ['k', 'K', 'º', '˛', 0],
		KeyL: ['l', 'L', '¬', 'ˇ', 0],
		KeyM: ['m', 'M', 'µ', 'Ú', 0],
		KeyN: ['n', 'N', '˜', 'Ó', 4],
		KeyO: ['o', 'O', 'ø', 'Ø', 0],
		KeyP: ['p', 'P', 'π', '∏', 0],
		KeyQ: ['q', 'Q', '„', '‚', 0],
		KeyR: ['r', 'R', '®', 'Ì', 0],
		KeyS: ['s', 'S', 'ß', '¯', 0],
		KeyT: ['t', 'T', '™', 'Ò', 0],
		KeyU: ['u', 'U', '¨', 'Ù', 4],
		KeyV: ['v', 'V', '√', 'É', 0],
		KeyW: ['w', 'W', 'Ω', 'À', 0],
		KeyX: ['x', 'X', '†', '‡', 0],
		KeyY: ['y', 'Y', 'æ', 'Æ', 0],
		KeyZ: ['z', 'Z', '∑', ' ', 0],
		Digit1: ['1', '!', '«', '»', 0],
		Digit2: ['2', '"', '“', '”', 0],
		Digit3: ['3', '£', '‘', '’', 0],
		Digit4: ['4', '$', '¥', '¢', 0],
		Digit5: ['5', '%', '~', '‰', 0],
		Digit6: ['6', '&', '‹', '›', 0],
		Digit7: ['7', '/', '÷', '⁄', 0],
		Digit8: ['8', '(', '´', '', 4],
		Digit9: ['9', ')', '`', ' ', 4],
		Digit0: ['0', '=', '≠', '≈', 0],
		Enter: [],
		EscApe: [],
		BAckspAce: [],
		TAb: [],
		SpAce: [' ', ' ', ' ', ' ', 0],
		Minus: ['\'', '?', '¡', '¿', 0],
		EquAl: ['ì', '^', 'ˆ', '±', 4],
		BrAcketLeft: ['è', 'é', '[', '{', 0],
		BrAcketRight: ['+', '*', ']', '}', 0],
		BAckslAsh: ['ù', '§', '¶', '◊', 0],
		Semicolon: ['ò', 'ç', '@', 'Ç', 0],
		Quote: ['à', '°', '#', '∞', 0],
		BAckquote: ['<', '>', '≤', '≥', 0],
		CommA: [',', ';', '…', ' ', 0],
		Period: ['.', ':', '•', '·', 0],
		SlAsh: ['-', '_', '–', '—', 0],
		CApsLock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		Insert: [],
		Home: [],
		PAgeUp: [],
		Delete: [],
		End: [],
		PAgeDown: [],
		ArrowRight: [],
		ArrowLeft: [],
		ArrowDown: [],
		ArrowUp: [],
		NumLock: [],
		NumpAdDivide: ['/', '/', '/', '/', 0],
		NumpAdMultiply: ['*', '*', '*', '*', 0],
		NumpAdSubtrAct: ['-', '-', '-', '-', 0],
		NumpAdAdd: ['+', '+', '+', '+', 0],
		NumpAdEnter: [],
		NumpAd1: ['1', '1', '1', '1', 0],
		NumpAd2: ['2', '2', '2', '2', 0],
		NumpAd3: ['3', '3', '3', '3', 0],
		NumpAd4: ['4', '4', '4', '4', 0],
		NumpAd5: ['5', '5', '5', '5', 0],
		NumpAd6: ['6', '6', '6', '6', 0],
		NumpAd7: ['7', '7', '7', '7', 0],
		NumpAd8: ['8', '8', '8', '8', 0],
		NumpAd9: ['9', '9', '9', '9', 0],
		NumpAd0: ['0', '0', '0', '0', 0],
		NumpAdDecimAl: [',', '.', ',', '.', 0],
		IntlBAckslAsh: ['\\', '|', '`', 'ı', 0],
		ContextMenu: [],
		NumpAdEquAl: ['=', '=', '=', '=', 0],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		AudioVolumeMute: [],
		AudioVolumeUp: ['', '=', '', '=', 0],
		AudioVolumeDown: [],
		NumpAdCommA: [],
		IntlRo: [],
		KAnAMode: [],
		IntlYen: [],
		ControlLeft: [],
		ShiftLeft: [],
		AltLeft: [],
		MetALeft: [],
		ControlRight: [],
		ShiftRight: [],
		AltRight: [],
		MetARight: []
	}
});
