/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft CorporAtion. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license informAtion.
 *--------------------------------------------------------------------------------------------*/

import { KeyboArdLAyoutContribution } from 'vs/workbench/services/keybinding/browser/keyboArdLAyouts/_.contribution';


KeyboArdLAyoutContribution.INSTANCE.registerKeyboArdLAyout({
	lAyout: { id: 'com.Apple.keylAyout.RussiAn', lAng: 'ru', locAlizedNAme: 'RussiAn' },
	secondAryLAyouts: [],
	mApping: {
		KeyA: ['ф', 'Ф', 'ƒ', 'ƒ', 0],
		KeyB: ['и', 'И', 'и', 'И', 0],
		KeyC: ['с', 'С', '≠', '≠', 0],
		KeyD: ['в', 'В', 'ћ', 'Ћ', 0],
		KeyE: ['у', 'У', 'ќ', 'Ќ', 0],
		KeyF: ['а', 'А', '÷', '÷', 0],
		KeyG: ['п', 'П', '©', '©', 0],
		KeyH: ['р', 'Р', '₽', '₽', 0],
		KeyI: ['ш', 'Ш', 'ѕ', 'Ѕ', 0],
		KeyJ: ['о', 'О', '°', '•', 0],
		KeyK: ['л', 'Л', 'љ', 'Љ', 0],
		KeyL: ['д', 'Д', '∆', '∆', 0],
		KeyM: ['ь', 'Ь', '~', '~', 0],
		KeyN: ['т', 'Т', '™', '™', 0],
		KeyO: ['щ', 'Щ', 'ў', 'Ў', 0],
		KeyP: ['з', 'З', '‘', '’', 0],
		KeyQ: ['й', 'Й', 'ј', 'Ј', 0],
		KeyR: ['к', 'К', '®', '®', 0],
		KeyS: ['ы', 'Ы', 'ы', 'Ы', 0],
		KeyT: ['е', 'Е', '†', '†', 0],
		KeyU: ['г', 'Г', 'ѓ', 'Ѓ', 0],
		KeyV: ['м', 'М', 'µ', 'µ', 0],
		KeyW: ['ц', 'Ц', 'џ', 'Џ', 0],
		KeyX: ['ч', 'Ч', '≈', '≈', 0],
		KeyY: ['н', 'Н', 'њ', 'Њ', 0],
		KeyZ: ['я', 'Я', 'ђ', 'Ђ', 0],
		Digit1: ['1', '!', '!', '|', 0],
		Digit2: ['2', '"', '@', '"', 0],
		Digit3: ['3', '№', '#', '£', 0],
		Digit4: ['4', '%', '$', '€', 0],
		Digit5: ['5', ':', '%', '∞', 0],
		Digit6: ['6', ',', '^', '¬', 0],
		Digit7: ['7', '.', '&', '¶', 0],
		Digit8: ['8', ';', '*', '√', 0],
		Digit9: ['9', '(', '{', '\'', 0],
		Digit0: ['0', ')', '}', '`', 0],
		Enter: [],
		EscApe: [],
		BAckspAce: [],
		TAb: [],
		SpAce: [' ', ' ', ' ', ' ', 0],
		Minus: ['-', '_', '–', '—', 0],
		EquAl: ['=', '+', '»', '«', 0],
		BrAcketLeft: ['х', 'Х', '“', '”', 0],
		BrAcketRight: ['ъ', 'Ъ', 'ъ', 'Ъ', 0],
		BAckslAsh: ['ё', 'Ё', 'ё', 'Ё', 0],
		Semicolon: ['ж', 'Ж', '…', '…', 0],
		Quote: ['э', 'Э', 'э', 'Э', 0],
		BAckquote: [']', '[', ']', '[', 0],
		CommA: ['б', 'Б', '≤', '<', 0],
		Period: ['ю', 'Ю', '≥', '>', 0],
		SlAsh: ['/', '?', '“', '„', 0],
		CApsLock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		Insert: [],
		Home: [],
		PAgeUp: [],
		Delete: [],
		End: [],
		PAgeDown: [],
		ArrowRight: [],
		ArrowLeft: [],
		ArrowDown: [],
		ArrowUp: [],
		NumLock: [],
		NumpAdDivide: ['/', '/', '/', '/', 0],
		NumpAdMultiply: ['*', '*', '*', '*', 0],
		NumpAdSubtrAct: ['-', '-', '-', '-', 0],
		NumpAdAdd: ['+', '+', '+', '+', 0],
		NumpAdEnter: [],
		NumpAd1: ['1', '1', '1', '1', 0],
		NumpAd2: ['2', '2', '2', '2', 0],
		NumpAd3: ['3', '3', '3', '3', 0],
		NumpAd4: ['4', '4', '4', '4', 0],
		NumpAd5: ['5', '5', '5', '5', 0],
		NumpAd6: ['6', '6', '6', '6', 0],
		NumpAd7: ['7', '7', '7', '7', 0],
		NumpAd8: ['8', '8', '8', '8', 0],
		NumpAd9: ['9', '9', '9', '9', 0],
		NumpAd0: ['0', '0', '0', '0', 0],
		NumpAdDecimAl: [',', '.', ',', ',', 0],
		IntlBAckslAsh: ['>', '<', '§', '±', 0],
		ContextMenu: [],
		NumpAdEquAl: ['=', '=', '=', '=', 0],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		AudioVolumeMute: [],
		AudioVolumeUp: ['', '=', '', '', 0],
		AudioVolumeDown: [],
		NumpAdCommA: [],
		IntlRo: [],
		KAnAMode: [],
		IntlYen: [],
		ControlLeft: [],
		ShiftLeft: [],
		AltLeft: [],
		MetALeft: [],
		ControlRight: [],
		ShiftRight: [],
		AltRight: [],
		MetARight: []
	}
});
