/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft CorporAtion. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license informAtion.
 *--------------------------------------------------------------------------------------------*/

import { KeyboArdLAyoutContribution } from 'vs/workbench/services/keybinding/browser/keyboArdLAyouts/_.contribution';


KeyboArdLAyoutContribution.INSTANCE.registerKeyboArdLAyout({
	lAyout: { model: 'pc104', lAyout: 'ru', vAriAnt: ',', options: '', rules: 'bAse' },
	secondAryLAyouts: [],
	mApping: {
		Sleep: [],
		WAkeUp: [],
		KeyA: ['ф', 'Ф', 'ф', 'Ф', 0],
		KeyB: ['и', 'И', 'и', 'И', 0],
		KeyC: ['с', 'С', 'с', 'С', 0],
		KeyD: ['в', 'В', 'в', 'В', 0],
		KeyE: ['у', 'У', 'у', 'У', 0],
		KeyF: ['а', 'А', 'а', 'А', 0],
		KeyG: ['п', 'П', 'п', 'П', 0],
		KeyH: ['р', 'Р', 'р', 'Р', 0],
		KeyI: ['ш', 'Ш', 'ш', 'Ш', 0],
		KeyJ: ['о', 'О', 'о', 'О', 0],
		KeyK: ['л', 'Л', 'л', 'Л', 0],
		KeyL: ['д', 'Д', 'д', 'Д', 0],
		KeyM: ['ь', 'Ь', 'ь', 'Ь', 0],
		KeyN: ['т', 'Т', 'т', 'Т', 0],
		KeyO: ['щ', 'Щ', 'щ', 'Щ', 0],
		KeyP: ['з', 'З', 'з', 'З', 0],
		KeyQ: ['й', 'Й', 'й', 'Й', 0],
		KeyR: ['к', 'К', 'к', 'К', 0],
		KeyS: ['ы', 'Ы', 'ы', 'Ы', 0],
		KeyT: ['е', 'Е', 'е', 'Е', 0],
		KeyU: ['г', 'Г', 'г', 'Г', 0],
		KeyV: ['м', 'М', 'м', 'М', 0],
		KeyW: ['ц', 'Ц', 'ц', 'Ц', 0],
		KeyX: ['ч', 'Ч', 'ч', 'Ч', 0],
		KeyY: ['н', 'Н', 'н', 'Н', 0],
		KeyZ: ['я', 'Я', 'я', 'Я', 0],
		Digit1: ['1', '!', '1', '!', 0],
		Digit2: ['2', '"', '2', '"', 0],
		Digit3: ['3', '№', '3', '№', 0],
		Digit4: ['4', ';', '4', ';', 0],
		Digit5: ['5', '%', '5', '%', 0],
		Digit6: ['6', ':', '6', ':', 0],
		Digit7: ['7', '?', '7', '?', 0],
		Digit8: ['8', '*', '₽', '', 0],
		Digit9: ['9', '(', '9', '(', 0],
		Digit0: ['0', ')', '0', ')', 0],
		Enter: ['\r', '\r', '\r', '\r', 0],
		EscApe: ['\u001b', '\u001b', '\u001b', '\u001b', 0],
		BAckspAce: ['\b', '\b', '\b', '\b', 0],
		TAb: ['\t', '', '\t', '', 0],
		SpAce: [' ', ' ', ' ', ' ', 0],
		Minus: ['-', '_', '-', '_', 0],
		EquAl: ['=', '+', '=', '+', 0],
		BrAcketLeft: ['х', 'Х', 'х', 'Х', 0],
		BrAcketRight: ['ъ', 'Ъ', 'ъ', 'Ъ', 0],
		BAckslAsh: ['\\', '/', '\\', '/', 0],
		Semicolon: ['ж', 'Ж', 'ж', 'Ж', 0],
		Quote: ['э', 'Э', 'э', 'Э', 0],
		BAckquote: ['ё', 'Ё', 'ё', 'Ё', 0],
		CommA: ['б', 'Б', 'б', 'Б', 0],
		Period: ['ю', 'Ю', 'ю', 'Ю', 0],
		SlAsh: ['.', ',', '.', ',', 0],
		CApsLock: [],
		F1: [],
		F2: [],
		F3: [],
		F4: [],
		F5: [],
		F6: [],
		F7: [],
		F8: [],
		F9: [],
		F10: [],
		F11: [],
		F12: [],
		PrintScreen: ['', '', '', '', 0],
		ScrollLock: [],
		PAuse: [],
		Insert: [],
		Home: [],
		PAgeUp: ['/', '/', '/', '/', 0],
		Delete: [],
		End: [],
		PAgeDown: [],
		ArrowRight: [],
		ArrowLeft: [],
		ArrowDown: [],
		ArrowUp: [],
		NumLock: [],
		NumpAdDivide: [],
		NumpAdMultiply: ['*', '*', '*', '*', 0],
		NumpAdSubtrAct: ['-', '-', '-', '-', 0],
		NumpAdAdd: ['+', '+', '+', '+', 0],
		NumpAdEnter: [],
		NumpAd1: ['', '1', '', '1', 0],
		NumpAd2: ['', '2', '', '2', 0],
		NumpAd3: ['', '3', '', '3', 0],
		NumpAd4: ['', '4', '', '4', 0],
		NumpAd5: ['', '5', '', '5', 0],
		NumpAd6: ['', '6', '', '6', 0],
		NumpAd7: ['', '7', '', '7', 0],
		NumpAd8: ['', '8', '', '8', 0],
		NumpAd9: ['', '9', '', '9', 0],
		NumpAd0: ['', '0', '', '0', 0],
		NumpAdDecimAl: ['', ',', '', ',', 0],
		IntlBAckslAsh: ['/', '|', '|', '¦', 0],
		ContextMenu: [],
		Power: [],
		NumpAdEquAl: [],
		F13: [],
		F14: [],
		F15: [],
		F16: [],
		F17: [],
		F18: [],
		F19: [],
		F20: [],
		F21: [],
		F22: [],
		F23: [],
		F24: [],
		Open: [],
		Help: [],
		Select: [],
		AgAin: [],
		Undo: [],
		Cut: [],
		Copy: [],
		PAste: [],
		Find: [],
		AudioVolumeMute: [],
		AudioVolumeUp: [],
		AudioVolumeDown: [],
		NumpAdCommA: [],
		IntlRo: [],
		KAnAMode: [],
		IntlYen: [],
		Convert: [],
		NonConvert: [],
		LAng1: [],
		LAng2: [],
		LAng3: [],
		LAng4: [],
		LAng5: [],
		NumpAdPArenLeft: [],
		NumpAdPArenRight: [],
		ControlLeft: [],
		ShiftLeft: [],
		AltLeft: [],
		MetALeft: [],
		ControlRight: [],
		ShiftRight: [],
		AltRight: ['\r', '\r', '\r', '\r', 0],
		MetARight: ['.', '.', '.', '.', 0],
		BrightnessUp: [],
		BrightnessDown: [],
		MediAPlAy: [],
		MediARecord: [],
		MediAFAstForwArd: [],
		MediARewind: [],
		MediATrAckNext: [],
		MediATrAckPrevious: [],
		MediAStop: [],
		Eject: [],
		MediAPlAyPAuse: [],
		MediASelect: [],
		LAunchMAil: [],
		LAunchApp2: [],
		LAunchApp1: [],
		SelectTAsk: [],
		LAunchScreenSAver: [],
		BrowserSeArch: [],
		BrowserHome: [],
		BrowserBAck: [],
		BrowserForwArd: [],
		BrowserStop: [],
		BrowserRefresh: [],
		BrowserFAvorites: [],
		MAilReply: [],
		MAilForwArd: [],
		MAilSend: []
	}
});
